# Generated by Django 4.2.3 on 2023-07-31 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
                ('name', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='Название категории')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=64, unique=True, verbose_name='URL')),
                ('title', models.CharField(max_length=128, unique=True, verbose_name='Заголовок')),
                ('text', models.TextField(verbose_name='Текст')),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Фото')),
                ('pub_time', models.DateTimeField(auto_now_add=True, verbose_name='Время публикации')),
                ('upd_time', models.DateTimeField(auto_now=True, verbose_name='Время редактирования')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликован')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='posts.category', verbose_name='Категория')),
            ],
        ),
    ]
